const express=require('express');const session=require('express-session');const {Pool}=require('pg');const bcrypt=require('bcryptjs');const multer=require('multer');const nodemailer=require('nodemailer');const crypto=require('crypto');
const app=express();const PORT=Number(process.env.PORT||3000);const ROOT=__dirname;const PUBLIC=ROOT+'/public';
if(!process.env.DATABASE_URL){console.error('DATABASE_URL is missing.');process.exit(1)}
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:5,connectionTimeoutMillis:15000,idleTimeoutMillis:30000});
const q=(sql,params=[])=>pool.query(sql,params);
async function init(){await q(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',theme_color TEXT NOT NULL DEFAULT '#9b7cff',background_url TEXT NOT NULL DEFAULT '',background_type TEXT NOT NULL DEFAULT 'image',audio_url TEXT NOT NULL DEFAULT '',avatar_url TEXT NOT NULL DEFAULT '',avatar_type TEXT NOT NULL DEFAULT 'image',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS badges(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,color TEXT NOT NULL DEFAULT '#9b7cff',equipped BOOLEAN NOT NULL DEFAULT FALSE);CREATE TABLE IF NOT EXISTS links(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,url TEXT NOT NULL,icon_url TEXT NOT NULL DEFAULT '');CREATE TABLE IF NOT EXISTS reset_codes(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,code_hash TEXT NOT NULL,expires_at TIMESTAMPTZ NOT NULL);`);console.log('Database initialized.')}
app.disable('x-powered-by');app.set('trust proxy',1);app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true}));app.use(session({secret:process.env.SESSION_SECRET||'change-this-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*24*60*60*1000}}));
function auth(req,res,next){if(!req.session.userId)return res.status(401).json({error:'Giriş yapman gerekiyor.'});next()}
async function userById(id){const r=await q('SELECT id,email,username,description,theme_color,background_url,background_type,audio_url,avatar_url,avatar_type FROM users WHERE id=$1',[id]);return r.rows[0]||null}
async function profile(username){const u=await q('SELECT id,username,description,theme_color,background_url,background_type,audio_url,avatar_url,avatar_type FROM users WHERE LOWER(username)=LOWER($1)',[username]);if(!u.rows[0])return null;const x=u.rows[0];const b=await q('SELECT id,name,color,equipped FROM badges WHERE user_id=$1 ORDER BY id DESC',[x.id]);const l=await q('SELECT id,name,url,icon_url FROM links WHERE user_id=$1 ORDER BY id DESC',[x.id]);return {username:x.username,description:x.description,themeColor:x.theme_color,backgroundUrl:x.background_url,backgroundType:x.background_type,audioUrl:x.audio_url,avatarUrl:x.avatar_url,avatarType:x.avatar_type,badges:b.rows,links:l.rows}}
app.get('/api/health',async(_req,res)=>{try{await q('SELECT 1');res.json({ok:true,service:'AEVIX'})}catch{res.status(503).json({ok:false})}});
app.post('/api/register',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),username=String(req.body.username||'').trim(),password=String(req.body.password||''),confirm=String(req.body.passwordConfirm||'');if(!email||!username||!password||password!==confirm)return res.status(400).json({error:'Alanları doldur ve şifreleri aynı gir.'});if(!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email)||!/^[a-zA-Z0-9_]{3,24}$/.test(username)||password.length<6)return res.status(400).json({error:'E-posta, kullanıcı adı veya şifre geçersiz.'});const ex=await q('SELECT id FROM users WHERE LOWER(email)=LOWER($1) OR LOWER(username)=LOWER($2)',[email,username]);if(ex.rows.length)return res.status(409).json({error:'Bu e-posta veya kullanıcı adı zaten kullanılıyor.'});const h=await bcrypt.hash(password,12),r=await q('INSERT INTO users(email,username,password_hash) VALUES($1,$2,$3) RETURNING id',[email,username,h]);req.session.userId=r.rows[0].id;res.json({ok:true})}catch(e){console.error(e);res.status(500).json({error:'Kayıt sırasında hata oluştu.'})}});
app.post('/api/login',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),r=await q('SELECT * FROM users WHERE LOWER(email)=LOWER($1)',[email]),u=r.rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'E-posta veya şifre yanlış.'});req.session.userId=u.id;res.json({ok:true})}catch(e){console.error(e);res.status(500).json({error:'Giriş sırasında hata oluştu.'})}});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/me',auth,async(req,res)=>{try{const user=await userById(req.session.userId);if(!user)return res.status(404).json({error:'Kullanıcı bulunamadı.'});const b=await q('SELECT id,name,color,equipped FROM badges WHERE user_id=$1 ORDER BY id DESC',[user.id]);const l=await q('SELECT id,name,url,icon_url FROM links WHERE user_id=$1 ORDER BY id DESC',[user.id]);res.json({user,badges:b.rows,links:l.rows})}catch(e){console.error(e);res.status(500).json({error:'Profil alınamadı.'})}});
app.post('/api/profile',auth,async(req,res)=>{const d=String(req.body.description||'').slice(0,1000),c=String(req.body.themeColor||'#9b7cff');if(!/^#[0-9a-fA-F]{6}$/.test(c))return res.status(400).json({error:'Geçersiz renk.'});try{await q('UPDATE users SET description=$1,theme_color=$2 WHERE id=$3',[d,c,req.session.userId]);res.json({ok:true})}catch(e){res.status(500).json({error:'Profil kaydedilemedi.'})}});
app.get('/api/profile/:username',async(req,res)=>{try{const p=await profile(req.params.username);if(!p)return res.status(404).json({error:'Profil bulunamadı.'});res.json(p)}catch(e){console.error(e);res.status(500).json({error:'Profil yüklenemedi.'})}});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:100*1024*1024},fileFilter:(_r,f,cb)=>{if(/^(image|video|audio)\//.test(f.mimetype))cb(null,true);else cb(new Error('Sadece resim, video veya ses dosyası yükleyebilirsin.'))}});
function storageConfig(){const base=(process.env.SUPABASE_URL||'').replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY;const bucket=process.env.SUPABASE_BUCKET||process.env.SUPABASE_STORAGE_BUCKET||'aevix';if(!base||!key)throw Error('Supabase Storage ayarları eksik: SUPABASE_URL ve SUPABASE_SERVICE_ROLE_KEY gerekli.');return {base,key,bucket}}
async function uploadSupabase(file,folder){const {base,key,bucket}=storageConfig();const ext=(file.originalname.match(/\.[A-Za-z0-9]{1,10}$/)||[''])[0].toLowerCase();const name=`${folder}/${crypto.randomBytes(20).toString('hex')}${ext}`;const r=await fetch(`${base}/storage/v1/object/${encodeURIComponent(bucket)}/${name}`,{method:'POST',headers:{Authorization:`Bearer ${key}`,apikey:key,'Content-Type':file.mimetype,'x-upsert':'true'},body:file.buffer});if(!r.ok){const t=await r.text();throw Error(`Supabase Storage yükleme hatası: ${t.slice(0,300)}`)}return `${base}/storage/v1/object/public/${encodeURIComponent(bucket)}/${name}`}
app.post('/api/upload',auth,upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'Dosya seçmedin.'});const type=String(req.body.type||'');if(!['background','avatar','audio'].includes(type))return res.status(400).json({error:'Geçersiz medya türü.'});const isV=req.file.mimetype.startsWith('video/'),isA=req.file.mimetype.startsWith('audio/');if(type==='audio'&&!isA)return res.status(400).json({error:'Müzik alanına sadece ses dosyası yükleyebilirsin.'});const url=await uploadSupabase(req.file,type);if(type==='background')await q('UPDATE users SET background_url=$1,background_type=$2 WHERE id=$3',[url,isV?'video':'image',req.session.userId]);if(type==='avatar')await q('UPDATE users SET avatar_url=$1,avatar_type=$2 WHERE id=$3',[url,isV?'video':'image',req.session.userId]);if(type==='audio')await q('UPDATE users SET audio_url=$1 WHERE id=$2',[url,req.session.userId]);res.json({ok:true,url})}catch(e){console.error('UPLOAD',e);res.status(400).json({error:e.message||'Dosya yüklenemedi.'})}});
app.post('/api/badges',auth,async(req,res)=>{const name=String(req.body.name||'').trim(),color=String(req.body.color||'');if(!name||name.length>20||!/^#[0-9a-fA-F]{6}$/.test(color))return res.status(400).json({error:'Rozet adı veya rengi geçersiz.'});try{const r=await q('INSERT INTO badges(user_id,name,color) VALUES($1,$2,$3) RETURNING id,name,color,equipped',[req.session.userId,name,color]);res.json(r.rows[0])}catch(e){res.status(500).json({error:'Rozet oluşturulamadı.'})}});
app.post('/api/badges/:id/equip',auth,async(req,res)=>{try{const r=await q('SELECT id FROM badges WHERE id=$1 AND user_id=$2',[req.params.id,req.session.userId]);if(!r.rows.length)return res.status(404).json({error:'Rozet bulunamadı.'});await q('UPDATE badges SET equipped=FALSE WHERE user_id=$1',[req.session.userId]);await q('UPDATE badges SET equipped=TRUE WHERE id=$1 AND user_id=$2',[req.params.id,req.session.userId]);res.json({ok:true})}catch(e){console.error(e);res.status(500).json({error:'Rozet kuşanılamadı.'})}});
app.post('/api/links',auth,async(req,res)=>{const name=String(req.body.name||'').trim().slice(0,80),url=String(req.body.url||'').trim(),icon=String(req.body.iconUrl||'').trim().slice(0,500);if(!name||!url)return res.status(400).json({error:'Bağlantı adı ve URL gerekli.'});try{for(const v of [url,icon].filter(Boolean)){const u=new URL(v);if(!['http:','https:'].includes(u.protocol))throw Error()}const r=await q('INSERT INTO links(user_id,name,url,icon_url) VALUES($1,$2,$3,$4) RETURNING id,name,url,icon_url',[req.session.userId,name,url,icon]);res.json(r.rows[0])}catch(e){res.status(400).json({error:'Geçerli bir http/https URL gir.'})}});
app.delete('/api/links/:id',auth,async(req,res)=>{try{await q('DELETE FROM links WHERE id=$1 AND user_id=$2',[req.params.id,req.session.userId]);res.json({ok:true})}catch(e){res.status(500).json({error:'Bağlantı silinemedi.'})}});
app.post('/api/request-reset',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),r=await q('SELECT id FROM users WHERE LOWER(email)=LOWER($1)',[email]);if(!r.rows.length)return res.json({ok:true,message:'Eğer bu e-posta kayıtlıysa kod gönderildi.'});const uid=r.rows[0].id,code=String(crypto.randomInt(100000,1000000)),hash=crypto.createHash('sha256').update(code).digest('hex');await q('DELETE FROM reset_codes WHERE user_id=$1',[uid]);await q(`INSERT INTO reset_codes(user_id,code_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '10 minutes')`,[uid,hash]);if(process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS){const tr=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:Number(process.env.SMTP_PORT||587)===465,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await tr.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:email,subject:'AEVIX şifre yenileme kodu',text:`AEVIX doğrulama kodun: ${code}`})}else console.log(`[AEVIX RESET CODE] ${email}: ${code}`);res.json({ok:true,message:'Eğer bu e-posta kayıtlıysa kod gönderildi.'})}catch(e){console.error(e);res.status(500).json({error:'Kod gönderilemedi.'})}});
app.post('/api/reset-password',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),code=String(req.body.code||'').trim(),pass=String(req.body.newPassword||'');if(!email||!/^[0-9]{6}$/.test(code)||pass.length<6)return res.status(400).json({error:'Geçersiz şifre sıfırlama isteği.'});const u=await q('SELECT id FROM users WHERE LOWER(email)=LOWER($1)',[email]);if(!u.rows.length)return res.status(400).json({error:'Kod geçersiz.'});const r=await q('SELECT * FROM reset_codes WHERE user_id=$1 AND expires_at>NOW() ORDER BY id DESC LIMIT 1',[u.rows[0].id]);if(!r.rows.length)return res.status(400).json({error:'Kod geçersiz veya süresi dolmuş.'});const h=crypto.createHash('sha256').update(code).digest('hex');if(h!==r.rows[0].code_hash)return res.status(400).json({error:'Kod geçersiz veya süresi dolmuş.'});await q('UPDATE users SET password_hash=$1 WHERE id=$2',[await bcrypt.hash(pass,12),u.rows[0].id]);await q('DELETE FROM reset_codes WHERE user_id=$1',[u.rows[0].id]);res.json({ok:true})}catch(e){console.error(e);res.status(500).json({error:'Şifre değiştirilemedi.'})}});
app.use(express.static(PUBLIC,{index:'index.html',maxAge:0}));
app.get('*splat',(req,res,next)=>{if(req.path.startsWith('/api/'))return next();res.sendFile(PUBLIC+'/index.html')});
app.use((err,_req,res,_next)=>{console.error(err);res.status(400).json({error:err.message||'Bir hata oluştu.'})});
(async()=>{try{await init();app.listen(PORT,'0.0.0.0',()=>console.log(`AEVIX running on port ${PORT}`))}catch(e){console.error('Startup failed',e);process.exit(1)}})();
